interfaces = []
exclude = [
    "**/*__pycache__",
    "**/*egg-info",
    "**/docs",
    "**/tests",
    "**/venv",
    "**/image",
]
source_roots = [
    "service/homelab-dagu-service/src",
    "service/homelab-restic-service/src",
    "service/homelab-barman-service/src",
    "service/homelab-extra-service/src",
    "service/homelab-apprise-service/src",
    "service/homelab-balite-service/src",
    "service/homelab-tailscale-service/src",
    "service/homelab-ddns-service/src",
    "service/homelab-traefik-service/src",
    "service/homelab-backup-service/src",
    "service/homelab-kanidm-service/src",
    "homelab-vpn/src",
    "config/homelab-s3-config/src",
    "config/homelab-dagu-config/src",
    "homelab-network/src",
    "homelab-global/src",
    "homelab-extract/src",
    "homelab-config/src",
    "homelab-pydantic/src",
    "config/homelab-traefik-config/src",
    "homelab-sequence/src",
    "homelab-docker/src",
    "homelab-backup/src",
    "homelab-secret/src",
    "homelab-s3/src",
    "homelab-mail/src",
]
