variables:
  OPENOBSERVE_URI:
    extract:
      kv:
        local:
          service: openobserve
          extract:
            svariable: HTTP_PORT
          transform:
            string:
              template: "http://openobserve:{value}"
    transform:
      string:
        template: "{local}"
  OPENOBSERVE_GRPC_URI:
    extract:
      kv:
        local:
          service: openobserve
          extract:
            svariable: GRPC_PORT
          transform:
            string:
              template: "openobserve:{value}"
    transform:
      string:
        template: "{local}"
