[project]
name = "homelab-restic-service"
version = "0.1.0"
authors = [{ name = "Vo Van Nghia", email = "git@vnghia.com" }]
requires-python = ">=3.13.1"
dependencies = [
    "homelab-pydantic",
    "homelab-backup",
    "homelab-docker",
    "homelab-barman-service",
    "homelab-balite-service",
    "homelab-litestream-service",
    "pulumi>=3.150.0",
    "homelab-extract",
    "homelab-dagu-config",
]

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[tool.ruff]
extend = "../../pyproject.toml"
