services:
  dozzle:
    depends-on:
      - host: sun
        service: dozzle
    config:
      traefik:
        dynamic:
          traefik:
            active: false
          agent:
            record: earth
    secrets:
      agent-key:
        active: false
      agent-cert:
        active: false
    container:
      active: false
    containers:
      agent:
        active: true
