services:
  traefik:
    variables:
      HTTP_PUBLIC_BIND_PORT: 80
      HTTPS_PUBLIC_BIND_PORT: 443
    config:
      entrypoint:
        config:
          private-https:
            middlewares:
              - local
        mapping:
          earth: "private-https"
    container:
      hosts:
        - host: sun
          internal: true
      wud:
