services:
  traefik:
    variables:
      HTTP_PUBLIC_BIND_PORT: 80
      HTTPS_PUBLIC_BIND_PORT: 443
    config:
      entrypoint:
        config:
          private-https:
            middlewares:
              http:
                - local
              tcp:
                - local-tcp
        mapping:
          earth: "private-https"
    container:
      wud:
