services:
  vector:
    network:
      bridge:
        egress:
          https:
            sun:
              host: sun
              hostnames:
                - hostname: openobserve
                  record: sun
