services:
  vector:
    network:
      bridge:
        proxy:
          egress:
            https:
              sun:
                host: sun
                hostnames:
                  - hostname: openobserve
                    record: sun
