docker:
  images:
    remote:
      airtrail:
        repo: johly/airtrail
        tag: "v3.6.0"
  volumes:
    local:
      airtrail-uploads: {}
services:
  kanidm:
    config:
      state:
        systems:
          oauth2:
            airtrail:
              display-name: AirTrail
              origin-url:
                - extract:
                    hostname: airtrail
                    record: solar
                    scheme: https
                  transform:
                    string:
                      template: "{value}/login"
              origin-landing:
                hostname: airtrail
                record: solar
                scheme: https
              prefer-short-username: true
              allow-insecure-client-disable-pkce: true
  airtrail:
    variables:
      PORT: 3000
    config:
      traefik:
        dynamic:
          traefik:
            record: solar
            service:
              port:
                svariable: PORT
    databases:
      postgres:
        postgres: {}
    keepasses:
      keepass:
        hostname:
          hostname: airtrail
          record: solar
    network:
      bridge:
        egress:
          https:
            api.adsbdb.com: null
            api.github.com: null
            raw.githubusercontent.com: null
            davidmegginson.github.io: null
            aerodatabox.p.rapidapi.com: null
    container:
      image: airtrail
      databases:
        - postgres:
          envs:
            env: DB_URL
      hosts:
        - record: solar
          hostname: kanidm
      tmpfs:
        - path: /tmp
          exec: true
      volumes:
        airtrail-uploads: /app/uploads
      wud:
        template: https://github.com/johanohly/AirTrail/releases/tag/${original}
        include-prefix: v
      envs:
        NODE_ENV: production
        ORIGIN:
          hostname: airtrail
          record: solar
          scheme: https
        OAUTH_ENABLED: true
        OAUTH_ISSUER_URL:
          extract:
            hostname: kanidm
            record: solar
            scheme: https
          transform:
            string:
              template: "{value}/oauth2/openid/airtrail/.well-known/openid-configuration"
        OAUTH_CLIENT_ID: airtrail
        OAUTH_CLIENT_SECRET:
          service: kanidm
          extract:
            export: airtrail
        OAUTH_AUTO_REGISTER: true
        OAUTH_AUTO_LOGIN: true
        OAUTH_HIDE_PASSWORD_FORM: true
        UPLOAD_LOCATION:
          volume: airtrail-uploads
