docker:
  images:
    build:
      barman:
        context:
          location: image/barman
          base: alpine
        args:
          BARMAN_VERSION: &barman-version "3.15.0-r0"
        version: *barman-version
  database:
    postgres:
      backup: {}
      container:
        network:
          bridge:
            barman: {}
  volumes:
    local:
      barman-home:
        backup: false
      barman-config:
        backup: false
services:
  barman:
    config:
      config-dir:
        volume: barman-config
      staging-dir:
        extract:
          volume: barman-home
        transform:
          path: staging
      minimum-redundancy: 3
      last-backup-maximum-age: 3 DAYS
      retention-policy: RECOVERY WINDOW OF 3 DAYS
      dagu:
        docker:
          executor:
            exec:
              container:
          dag:
            params:
              types:
                backup:
            tags: ["backup"]
          command:
            prefix: ["barman"]
            suffix:
              - param:
                  type: backup
          dags:
            check:
              dag:
                schedule: "0 5 */3 * *"
              command: ["check"]
            backup:
              command: ["backup", "--wait"]
            switch-wal:
              command: ["switch-wal", "--force", "--archive"]
        dag:
          restore:
            name: restore
            path: barman-restore
            params:
              types:
                backup:
                snapshot:
            tags: ["backup"]
            steps:
              - name: restore
                executor:
                  container:
                run:
                  - "restore"
                  - param:
                      type: backup
                  - param:
                      type: snapshot
    container:
      image:
        build: barman
      init: true
      tmpfs:
        - /tmp
        - /var/run
      volumes:
        barman-config:
          path: /etc/barman.d
          read-only: true
        barman-home: /var/lib/barman
