docker:
  images:
    remote:
      bitmagnet:
        repo: ghcr.io/bitmagnet-io/bitmagnet
        tag: "v0.10.0"
services:
  bitmagnet:
    variables:
      PORT: 3333
    config:
      traefik:
        dynamic:
          traefik:
            record: earth
            service:
              port:
                svariable: PORT
    databases:
      postgres:
        postgres:
          config:
            backup:
              minimum-redundancy: 1
              last-backup-maximum-age: 1 DAYS
              retention-policy: REDUNDANCY 1
    network:
      vpn:
        ports:
          port:
        envs:
          DNS_KEEP_NAMESERVER: "on"
    container:
      image: bitmagnet
      network:
        container: vpn
      command:
        - worker
        - run
        - --all
      databases:
        - postgres:
          envs:
            env: POSTGRES_DSN
      wud:
        template: https://github.com/bitmagnet-io/bitmagnet/releases/tag/${original}
        include-prefix: v
      envs:
        DHT_SERVER_PORT:
          port:
        HTTP_SERVER_LOCAL_ADDRESS:
          extract:
            svariable: PORT
          transform:
            string:
              template: ":{value}"
        LOG_LEVEL: info
        LOG_JSON: true
