docker:
  images:
    remote:
      convos:
        repo: ghcr.io/convos-chat/convos
        tag: "v8.07"
  volumes:
    local:
      convos-data: {}
services:
  kanidm:
    config:
      state:
        systems:
          oauth2:
            kanidm:
              origin-url:
                - extract:
                    hostname: convos
                    record: solar
                    scheme: https
                  transform:
                    string:
                      template: "{value}/oidc/callback"
  convos:
    variables:
      PORT: 3000
    config:
      traefik:
        dynamic:
          traefik:
            record: solar
            service:
              port:
                svariable: PORT
            middlewares:
              - service: traefik
                name: oidc
    keepasses:
      keepass:
        hostname:
          hostname: convos
          record: solar
    secrets:
      local: {}
    container:
      experimental: true
      image: convos
      network:
        bridge:
          vpn: {}
      volumes:
        convos-data: /data
      wud:
        template: https://github.com/convos-chat/convos/releases/tag/${original}
        include-prefix: v
        semver-count: 2
      envs:
        CONVOS_LOCAL_SECRET:
          secret: local
        CONVOS_REVERSE_PROXY: 1
        CONVOS_PLUGINS: "Convos::Plugin::Auth::Header"
        CONVOS_AUTH_HEADER: X-Remote-Email
