docker:
  images:
    remote:
      ddns:
        repo: ghcr.io/qdm12/ddns-updater
        tag: "v2.9.0"
  volumes:
    local:
      ddns-data: {}
services:
  ddns:
    variables:
      PORT: 8000
    config:
      traefik:
        dynamic:
          traefik:
            service:
              port:
                svariable: PORT
    container:
      image: ddns
      healthcheck: {}
      network:
        bridge:
          default: {}
      volumes:
        ddns-data: /updater/data
      wait_timeout: 300
      wud:
        template: https://github.com/qdm12/ddns-updater/releases/tag/${original}
        include-prefix: v
      envs:
        LISTENING_ADDRESS:
          extract:
            svariable: PORT
          transform:
            string:
              template: ":{value}"
        DATADIR:
          volume: ddns-data
        RESOLVER_ADDRESS: "1.1.1.1:53"
