docker:
  images:
    remote:
      flaresolverr:
        repo: ghcr.io/flaresolverr/flaresolverr
        tag: "v3.4.5"
services:
  flaresolverr:
    config: {}
    container:
      image: flaresolverr
      network:
        bridge:
          vpn: {}
      read-only: false
      wud:
        template: https://github.com/FlareSolverr/FlareSolverr/releases/tag/${original}
        include-prefix: v
      envs:
        PORT: 8191
