docker:
  network:
    vpn:
      service: gluetun
  images:
    remote:
      gluetun:
        repo: ghcr.io/qdm12/gluetun
        tag: "v3.41.1"
services:
  gluetun:
    config: {}
    network:
      bridge:
    container:
      active: false
      image: gluetun
      cap:
        add:
          - DAC_OVERRIDE
          - MKNOD
          - NET_ADMIN
          - NET_RAW
      healthcheck:
        interval: 30
        retries: 1
      network:
        bridge:
          default: {}
      read-only: false
      user: root
      wud:
        template: https://github.com/qdm12/gluetun/releases/tag/${original}
        include-prefix: v
      envs:
        DNS_UPSTREAM_RESOLVERS: cloudflare,libredns,opendns,quad9
        DNS_UPSTREAM_IPV6: "on"
