docker:
  network:
    vpn:
      service: gluetun
  images:
    remote:
      gluetun:
        repo: ghcr.io/qdm12/gluetun
        tag: "v3.40.0"
services:
  gluetun:
    config: {}
    network:
      bridge:
    container:
      active: false
      image: gluetun
      capabilities:
        - NET_ADMIN
      healthcheck:
        tests: ["CMD", "/gluetun-entrypoint", "healthcheck"]
        interval: 30s
        timeout: 5s
        retries: 1
        start-period: 10s
      network:
        bridge:
          default: {}
      read-only: false
      wud:
        template: https://github.com/qdm12/gluetun/releases/tag/${original}
        include-prefix: v
      envs:
        DOT: "off"
