docker:
  images:
    remote:
      homea:
        repo: ghcr.io/home-assistant/home-assistant
        tag: "2025.12.4"
  volumes:
    local:
      homea-config: {}
services:
  homea:
    variables:
      PORT: 8123
    config:
      traefik:
        dynamic:
          traefik:
            service:
              port:
                svariable: PORT
    keepasses:
      keepass:
        username:
          length: 16
          special: false
          upper: false
        hostname:
          hostname: homea
    user: root
    container:
      image: homea
      cap:
        add:
          - NET_ADMIN
          - NET_RAW
      network:
        bridge:
          vpn: {}
      privileged: true
      tmpfs:
        - path: /run
          exec: true
        - path: /tmp
      volumes:
        homea-config: /config
        "/run/dbus":
          path: /run/dbus
          read-only: true
      wud:
        template: https://www.home-assistant.io/changelogs/core-${major}.${minor}
