users:
  root:
    uid: 0
    gid: 0
  user:
    uid: 1000
    gid: 1000
  docker:
variables:
  FULL_HOSTNAME:
    extract:
      kv:
        project:
          extract:
            project:
          transform:
            string:
              template: "{project}-{stack}"
        host:
          hinfo: name
    transform:
      string:
        template: "{project}-{host}"
