docker:
  images:
    remote:
      alpine:
        repo: alpine
        tag: "3.23.0"
      python-alpine:
        repo: python
        tag: "3.14.2-alpine3.23"
      python-builder:
        repo: ghcr.io/astral-sh/uv
        tag: "0.9.17-python3.14-alpine"
