docker:
  images:
    remote:
      impress-backend:
        repo: lasuite/impress-backend
        tag: &impress-version "v3.7.0"
      impress-frontend:
        repo: lasuite/impress-frontend
        tag: *impress-version
      impress-collaboration:
        repo: lasuite/impress-y-provider
        tag: *impress-version
services:
  kanidm:
    config:
      state:
        systems:
          oauth2:
            impress:
              display-name: Impress
              origin-url:
                - extract:
                    hostname: impress
                    record: solar
                    scheme: https
                  transform:
                    string:
                      template: "{value}/api/v1.0/callback/"
              origin-landing:
                hostname: impress
                record: solar
                scheme: https
              prefer-short-username: true
  impress:
    variables:
      BACKEND_PORT: 8000
      FRONTEND_PORT: 3000
      COLLABORATION_PORT: 4444
      OAUTH_URL:
        extract:
          hostname: kanidm
          record: solar
          scheme: https
        transform:
          string:
            template: "{value}/oauth2/openid/impress"
    config:
      traefik:
        dynamic:
          backend:
            name: backend
            hostname: impress
            record: solar
            rules:
              - (PathPrefix(`/api`) || PathPrefix(`/admin`))
            service:
              container: backend
              port:
                svariable: BACKEND_PORT
          frontend:
            name: frontend
            hostname: impress
            record: solar
            service:
              container: frontend
              port:
                svariable: FRONTEND_PORT
          collaboration:
            name: collaboration
            hostname: impress
            record: solar
            prefix: /collaboration
            service:
              container: collaboration
              port:
                svariable: COLLABORATION_PORT
      s3:
        backend:
    databases:
      postgres:
        postgres: {}
      valkey:
        valkey: {}
    secrets:
      django: {}
      collaboration: {}
    containers:
      backend:
        image: impress-backend
        databases:
          - postgres:
            envs:
              username: DB_USER
              password: DB_PASSWORD
              database: DB_NAME
              host: DB_HOST
              port: DB_PORT
          - valkey:
            envs:
              env: REDIS_URL
              database: 1
          - valkey:
            envs:
              env: DJANGO_CELERY_BROKER_URL
              database: 0
        network:
          bridge:
            default: {}
        tmpfs:
          - /tmp
        wud:
          template: https://github.com/suitenumerique/docs/releases/tag/${original}
          include-prefix: v
        envs:
          # TODO: Configure OIDC properly after https://github.com/suitenumerique/docs/issues/1186
          DJANGO_ALLOWED_HOSTS:
            hostname: impress
            record: solar
          DJANGO_CSRF_TRUSTED_ORIGINS:
            hostname: impress
            record: solar
            scheme: https
          DJANGO_SECRET_KEY:
            secret: django
          DJANGO_SETTINGS_MODULE: impress.settings
          DJANGO_CONFIGURATION: Production
          OIDC_CREATE_USER: true
          OIDC_RP_SIGN_ALGO: ES256
          OIDC_RP_CLIENT_ID: impress
          OIDC_RP_CLIENT_SECRET:
            service: kanidm
            extract:
              export: impress
          OIDC_OP_JWKS_ENDPOINT:
            extract:
              svariable: OAUTH_URL
            transform:
              string:
                template: "{value}/public_key.jwk"
          OIDC_OP_AUTHORIZATION_ENDPOINT:
            extract:
              hostname: kanidm
              record: solar
              scheme: https
            transform:
              string:
                template: "{value}/ui/oauth2"
          OIDC_OP_TOKEN_ENDPOINT:
            extract:
              hostname: kanidm
              record: solar
              scheme: https
            transform:
              string:
                template: "{value}/oauth2/token"
          OIDC_OP_USER_ENDPOINT:
            extract:
              svariable: OAUTH_URL
            transform:
              string:
                template: "{value}/userinfo"
          OIDC_OP_LOGOUT_ENDPOINT:
            extract:
              hostname: kanidm
              record: solar
              scheme: https
            transform:
              string:
                template: "{value}/oauth2/token/revoke"
          OIDC_RP_SCOPES: openid profile email
          LOGIN_REDIRECT_URL:
            hostname: impress
            record: solar
            scheme: https
          LOGIN_REDIRECT_URL_FAILURE:
            hostname: impress
            record: solar
            scheme: https
          LOGOUT_REDIRECT_URL:
            hostname: impress
            record: solar
            scheme: https
          OIDC_USE_NONCE: false
          OIDC_USE_PKCE: true
          OIDC_REDIRECT_REQUIRE_HTTPS: true
          OIDC_REDIRECT_ALLOWED_HOSTS:
            hostname: impress
            record: solar
            scheme: "https"
          OIDC_FALLBACK_TO_EMAIL_FOR_IDENTIFICATION: false
          OIDC_STORE_ACCESS_TOKEN: true
          OIDC_USERINFO_FULLNAME_FIELDS: name
          OIDC_USERINFO_SHORTNAME_FIELD: preferred_username
          FRONTEND_HOMEPAGE_FEATURE_ENABLED: false
          COLLABORATION_SERVER_SECRET:
            secret: collaboration
          COLLABORATION_API_URL:
            extract:
              hostname: impress
              record: solar
              scheme: https
            transform:
              string:
                template: "{value}/collaboration/api/"
          COLLABORATION_WS_URL:
            extract:
              hostname: impress
              record: solar
              scheme: wss
            transform:
              string:
                template: "{value}/collaboration/ws/"
          Y_PROVIDER_API_BASE_URL:
            extract:
              svariable: COLLABORATION_PORT
            transform:
              string:
                template: "http://impress-collaboration:{value}/api"
          Y_PROVIDER_API_KEY:
            secret: collaboration
      frontend:
        image: impress-frontend
        tmpfs:
          - /tmp
      collaboration:
        image: impress-collaboration
        tmpfs:
          - /tmp
          - /.yarn
        envs:
          COLLABORATION_LOGGING: true
          COLLABORATION_SERVER_ORIGIN:
            hostname: impress
            record: solar
            scheme: https
          COLLABORATION_BACKEND_BASE_URL:
            hostname: impress
            record: solar
            scheme: https
          COLLABORATION_SERVER_SECRET:
            secret: collaboration
          Y_PROVIDER_API_KEY:
            secret: collaboration
