docker:
  images:
    remote:
      livekit:
        repo: livekit/livekit-server
        tag: "v1.9.8"
services:
  livekit:
    variables:
      PORT: &port 7880
      TCP_PORT: &tcp-port 7881
      UDP_PORT_START: &udp-port-start 50000
      UDP_PORT_END: &udp-port-end 50200
    config:
      traefik:
        dynamic:
          traefik:
            record: solar
            service:
              port:
                svariable: PORT
    databases:
      valkey:
        valkey: {}
    container:
      image: livekit
      network:
        bridge:
          default: {}
      ports:
        livekit-tcp:
          internal: *tcp-port
          protocol: tcp
        livekit-udp:
          range:
            - *udp-port-start
            - *udp-port-end
          protocol: udp
      wud:
        template: https://github.com/livekit/livekit/releases/tag/${original}
        include-prefix: v
      envs:
        LIVEKIT_CONFIG:
          format: yaml
          data:
            port: *port
            rtc:
              tcp_port: *tcp-port
              port_range_start: *udp-port-start
              port_range_end: *udp-port-end
              use_external_ip: true
            redis:
              address:
                extract:
                  type: valkey
                  info: [host, port]
                transform:
                  string:
                    template: "{host}:{port}"
              password:
                type: valkey
                info: password
