docker:
  images:
    remote:
      maybe:
        repo: ghcr.io/maybe-finance/maybe
        tag: "0.6.0"
  volumes:
    local:
      maybe-storage: {}
services:
  maybe:
    config:
      traefik:
        dynamic:
          traefik:
            record: solar
            service:
              port:
                env: PORT
    databases:
      postgres:
        postgres: {}
      valkey:
        valkey: {}
    keepasses:
      keepass:
        hostname:
          hostname: maybe
          record: solar
    secrets:
      key: {}
    container:
      image: maybe
      databases:
        - postgres:
          envs:
            username: POSTGRES_USER
            password: POSTGRES_PASSWORD
            database: POSTGRES_DB
            host: DB_HOST
            port: DB_PORT
        - valkey:
          envs:
            env: REDIS_URL
      network:
        bridge:
          default: {}
      tmpfs:
        - /tmp
        - /rails/tmp/sockets
      volumes:
        maybe-storage: /rails/storage
      wud:
        template: https://github.com/maybe-finance/maybe/releases/tag/v${original}
      envs:
        SELF_HOSTED: true
        RAILS_FORCE_SSL: false
        RAILS_ASSUME_SSL: true
        SECRET_KEY_BASE:
          secret: key
        PORT: 3000
        APP_DOMAIN:
          hostname: maybe
          record: solar
    containers:
      worker:
        inherit:
        command: ["bundle", "exec", "sidekiq"]
        network:
          bridge:
            default:
              active: false
        wud:
