docker:
  images:
    remote:
      meilisearch:
        repo: getmeili/meilisearch
        tag: "v1.15.2"
services:
  meilisearch:
    config: {}
    container:
      active: false
      delete-before-replace: true
      image: meilisearch
      healthcheck:
        tests:
          - "CMD"
          - "wget"
          - "--spider"
          - "-q"
          - extract:
              svariable: MELISEARCH_PORT
            transform:
              string:
                template: "http://0.0.0.0:{value}/health"
      tmpfs:
        - /tmp
      user: default
      envs:
        MEILI_DB_PATH:
          extract:
            svariable: MELISEARCH_VOLUME
          transform:
            path: data.ms
        MEILI_ENV: production
        MEILI_HTTP_ADDR:
          extract:
            svariable: MELISEARCH_PORT
          transform:
            string:
              template: "0.0.0.0:{value}"
        MEILI_MASTER_KEY:
          secret: meilisearch-key
        MEILI_NO_ANALYTICS: true
        MEILI_DUMP_DIR:
          extract:
            svariable: MELISEARCH_VOLUME
          transform:
            path: dumps
        MEILI_SCHEDULE_SNAPSHOT: 86400
        MEILI_SNAPSHOT_DIR:
          extract:
            svariable: MELISEARCH_VOLUME
          transform:
            path: snapshots
