docker:
  database:
    mysql:
      images:
        mysql:
          "11":
            repo: mariadb
            tag: "11.8.6-ubi9"
      version: 11
      port: 3306
      dir:
        data: /var/lib/mysql
        initdb: /docker-entrypoint-initdb.d
      env:
        username: MARIADB_USER
        password: MARIADB_PASSWORD
        database: MARIADB_DATABASE
        data-dir: DATADIR
        superuser-password: MARIADB_ROOT_PASSWORD
      container:
        command:
          [
            "--character-set-server=utf8mb4",
            "--collation-server=utf8mb4_unicode_ci",
          ]
        healthcheck:
          tests: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
        tmpfs:
          - /tmp
          - /run/mariadb
        envs:
          MARIADB_AUTO_UPGRADE: true
