docker:
  network:
    bridge:
      host:
        default:
          icc: false
        internal:
          internal: true
        vpn:
          ipam:
          icc: false
      service:
    default:
      bridge:
        internal: {}
