docker:
  images:
    remote:
      nginx-static:
        repo: ghcr.io/docker-nginx-static/nginx-static
        tag: "latest"
        delete-before-replace: true
services:
  nginx-static:
    variables:
      PORT: 80
    config: {}
    network:
      bridge:
    container:
      image: nginx-static
      active: false
      tmpfs:
        - /var/cache/nginx
        - /var/run
