docker:
  images:
    remote:
      qbittorrent:
        repo: ghcr.io/linuxserver/qbittorrent
        tag: "5.1.4"
  volumes:
    local:
      qbittorrent-config: {}
      qbittorrent-downloads:
        backup: false
      qbittorrent-starr:
        backup: false
services:
  qbittorrent:
    config:
      traefik:
        dynamic:
          traefik:
            service:
              port:
                env: WEBUI_PORT
    keepasses:
      keepass:
        hostname:
          hostname: qbittorrent
    network:
      vpn:
        ports:
          port:
    container:
      image: qbittorrent
      network:
        container: vpn
      tmpfs:
        - path: /run
          exec: true
      volumes:
        qbittorrent-config: /config
        qbittorrent-downloads: /downloads
        qbittorrent-starr: /starr/sources/torrents
      envs:
        S6_READ_ONLY_ROOT: 1
        WEBUI_PORT: 8080
        TORRENTING_PORT:
          port:
      wud:
        # See https://github.com/getwud/wud/issues/498 for context.
        # To be revisited when qbittorrent reaches 14th version.
        exclude: "^(14|20).*$"
