docker:
  database:
    redis:
      images:
        redis:
          "7":
            repo: bitnami/redis
            tag: "7.4.2"
      version: 7
      port: 6379
      dir:
        data: /bitnami/redis/data
        tmp: /opt/bitnami/redis
      env:
        password: REDIS_PASSWORD
        database: REDIS_DATABASE
        data-dir: REDIS_DATA_DIR
      container:
        healthcheck:
          tests:
            - "CMD"
            - "redis-cli"
            - "--raw"
            - "incr"
            - "ping"
