records:
  sun:
    records:
      xseed:
        routable: false
  earth:
    records:
      docker-proxy:
        routable: false
      dozzle:
        routable: false
      dagu:
        routable: false
